In [3]:
import pandas as pd

In [13]:
probasA = pd.read_csv('predict_probas/xgb_baseline.csv', index_col='building_id')
probasB = pd.read_csv('predict_probas/xgb_short1_ambos_geos.csv', index_col='building_id')
probasC = pd.read_csv('predict_probas/catboost_2000_iterations.csv', index_col='building_id')
probasD = pd.read_csv('predict_probas/knn_sin_outliers43.csv', index_col='building_id')

In [14]:
pesoA = 469
pesoB = 460
pesoC = 395
pesoD = 348

In [15]:
merged = probasA.merge(probasB, right_index=True, left_index=True)\
        .merge(probasC, right_index=True, left_index=True)\
        .merge(probasD, right_index=True, left_index=True)

In [16]:
merged

,A1,A2,A3,B1,B2,B3,C1,C2,C3,D1,D2,D3
building_id,,,,,,,,,,,,
300051,0.000780,0.331764,0.667456,0.001447,0.179194,0.819359,0.002898,0.170795,0.826307,0.000000,0.000000,1.000000
99355,0.000370,0.918881,0.080749,0.000085,0.999747,0.000168,0.000513,0.996017,0.003469,0.000000,1.000000,0.000000
890251,0.002469,0.688705,0.308826,0.000794,0.008592,0.990614,0.008463,0.040695,0.950842,0.000000,0.000000,1.000000
745817,0.610141,0.389605,0.000254,0.646447,0.353053,0.000500,0.676872,0.322624,0.000504,0.522753,0.477247,0.000000
421793,0.001014,0.283388,0.715598,0.000286,0.170128,0.829586,0.000392,0.165270,0.834338,0.000000,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
310028,0.128420,0.816672,0.054907,0.053498,0.897182,0.049320,0.056889,0.888797,0.054314,0.000000,1.000000,0.000000
663567,0.000363,0.661962,0.337675,0.000324,0.388023,0.611653,0.000397,0.191132,0.808472,0.000000,0.000000,1.000000
1049160,0.033297,0.743029,0.223674,0.035169,0.951833,0.012998,0.050840,0.906344,0.042815,0.000000,1.000000,0.000000
442785,0.002030,0.820695,0.177274,0.017887,0.821603,0.160510,0.030775,0.725005,0.244219,0.000000,0.934914,0.065086
501372,0.412958,0.579516,0.007526,0.517616,0.452903,0.029481,0.597895,0.332965,0.069140,0.882377,0.117623,0.000000

In [17]:
merged[1] = merged.A1 * pesoA + merged.B1 * pesoB + merged.C1 * pesoC + merged.D1 * pesoD
merged[2] = merged.A2 * pesoA + merged.B2 * pesoB + merged.C2 * pesoC + merged.D2 * pesoD
merged[3] = merged.A3 * pesoA + merged.B3 * pesoB + merged.C3 * pesoC + merged.D3 * pesoD

In [18]:
merged[[1,2,3]]

                       1            2            3
building_id
300051          2.176125   305.490893  1364.332999
99355           0.415399  1632.265267    39.319314
890251          4.866442   343.029395  1324.104188
745817       1032.804042   638.647530     0.548420
421793          0.761922   276.449251  1394.788807
...                  ...          ...          ...
310028        107.309394  1494.798092    69.892499
663567          0.475935   564.447553  1107.076504
1049160        51.876165  1492.329840   127.793982
442785         21.336396  1374.570805   276.092816
501372        975.016458   652.582518    44.401017

[86868 rows x 3 columns]

In [19]:
prediction = merged[[1,2,3]].idxmax(axis="columns")

In [20]:
submission_format = pd.read_csv('submission_format.csv', index_col='building_id')
my_submission = pd.DataFrame(data=prediction,
                             columns=submission_format.columns,
                             index=submission_format.index)

In [21]:
my_submission.to_csv('subs/ensable_segun_score.csv')